### ISSUE TITLE
HDS Support

### ISSUE THREAD

**Issue by titpetric** [WowzaMediaSystems/wse-example-pushpublish-hls#1]
Hi,

Akamai points support HDS as well as HLS ingests, would it be possible to include the HDS counterpoint to HLS pushpublish example?

Best,
Tit

**Comment by Cheleri** [comment]
Hi Tit,

We do not currently have an customizable version of the HDS push publishing profile on the schedule.  I will let our product owner know of your request.

Sincerely,
Eric
