### ISSUE TITLE
 I can not upload to WebDav server

### ISSUE THREAD

**Issue by speedracer1126** [WowzaMediaSystems/wse-example-pushpublish-hls#16]
We use this code to push files from the WOWZA server to the WebDAV server.
This code is intended to create and upload a new collection on a WebDAV server, but when uploading, MKCOL does not run and the file is not uploaded with an error.
As a trial, the required collection has been created manually and uploaded.
Is there any code resolved for this issue?

**Comment by akeller** [comment]
Hi there - What error are you seeing?

**Comment by Wowza-Rose** [comment]
I am curious if you are attempting this through a trial Engine license as that has certain restrictions. Sorry for the late response on this.
