### ISSUE TITLE
Error when cupertinoMinPlaylistChunkCount > 1

### ISSUE THREAD

**Issue by jordicenzano** [WowzaMediaSystems/wse-example-pushpublish-hls#2]
if you use the code of this repo and you set this app configuration parameter `cupertinoMinPlaylistChunkCount` to a value X (X > 1) (it is useful to avoid 1st segment with negative duration). Then I'm getting this error for the first X chunks:

```
ERROR server comment - PushPublish.createOutputItem(live/_definst_/alive_source->profile_0) : java.lang.NullPointerException|at com.wowza.wms.pushpublish.protocol.cupertino.PushPublishHTTPCupertino.createOutputItem(PushPublishHTTPCupertino.java:653)|at com.wowza.wms.pushpublish.model.PushPublishHTTPPusher$HTTPPoller.run(PushPublishHTTPPusher.java:197)|
ERROR server comment - PushPublish.outputSend(live/_definst_/alive_source->profile_0) Unable to clone maseter playlist. : java.lang.NullPointerException|at com.wowza.wms.pushpublish.protocol.cupertino.PushPublishHTTPCupertino.outputSend(PushPublishHTTPCupertino.java:752)|at com.wowza.wms.pushpublish.model.PushPublishHTTPPusher$OutputRunner.run(PushPublishHTTPPusher.java:275)|at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)|at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)|at java.lang.Thread.run(Thread.java:745)|
```

**Comment by Cheleri** [comment]
Hi jordicenzano,

This appears to be a bug in the core code of the Wowza Streaming Engine.  I've opened a bug for you in our support ticketing system.  You should be getting an email regarding it soon.

Thanks for flagging this for us.

Eric

**Comment by Cheleri** [comment]
The ticket is 194023

Eric

**Comment by Cheleri** [comment]
Hi Jordi,

There was a fix posted for this in the ticket reference above, you can go get a download with the fix from there.  It will be made available to the public in our next public release (after 4.5.0.02 release, it did not make it into that release).

Thanks,
Eric
