### ISSUE TITLE
PushPublishHTTPCupertino gets stalled when upload takes longer than expected

### ISSUE THREAD

**Issue by jordicenzano** [WowzaMediaSystems/wse-example-pushpublish-hls#3]
Hi, I have found a really concerning issue in that code, and it is easy to reproduce.

Context:
- In our implementation we are uploading the chunks to S3 instead of writing them to local disc.
- Inside this function we upload the segment to s3: `public int sendMediaSegment(MediaSegmentModel mediaSegment)`

Problem:
- When we hit an unhealthy S3 entry point and the chunk uploading takes longer than expected (easy to simulate with `Sleep (40000)`), we start seeing these logs lines for every new chunk:
```
WARN server comment - PushPublishHTTPPusher#HTTPPoller.addOutput[live/_definst_/alive_160p[profile_1]]: items queued:28
INFO server comment - PushPublish.updateMediaSegmentPlaybackURI(live/_definst_/alive_160p->profile_1)  Path: media_43.ts
```
But the HUGE PROBLEM is that since that point **none of the send functions are called**, such as: sendMediaSegment, sendMediaPlaylist
- The result is that because 1 chunk took longer to upload all the system (the pushpublish) gets stalled and wowza end up crashing after few hours.

**Comment by curleypg** [comment]
I'm also experiencing similar issues with this module and a custom solution to upload live HLS content using Wowza Media Engine 4.5.0.

Is there any way to "kickstart" the sendMediaSegment method when chunks are beginning to be queued by PushPublishHTTPPusher#HTTPPoller.addOutput ?

**Comment by rogerlittin** [comment]
Hi,

As with any threaded application that has the potential to stall due to issues downstream, you should probably create a separate thread pool to handle the uploading tasks so that you aren't stalling the main push publisher thread. Instead of performing  the upload directly in the send* methods, create an upload task and offload them to your own thread pool.
