### ISSUE TITLE
Sample implementation

### ISSUE THREAD

**Issue by inzifusa** [WowzaMediaSystems/wse-example-pushpublish-hls#4]
Hi,

I've followed your instructions for adding a custom Apple HLS profile. I've used your custom implementation (PushPublishProfilesCustom.xml and .jar) but I can't see the stream targets.

Could you please help me to understand if there are other settings that I should modify?
Finally, is it possible to use another destination instead local disk?

Thank you very much for your help.

Best regards,

Silvia

**Comment by Cheleri** [comment]
Hi Silvia,

Your custom target will not show up in the Wowza Streaming Engine Manager.  You can add entries both programmatically using the IPushPublishManager interface (see WowzaStreamingEngine_ServerSideAPI.pdf that came with your installation) or you can add entries using a text editor (not recommended in that this is error prone, but if you are careful, you can do it).

To get a reference to the current IPushPublishManger, do something like:

    IVHost iVhost = (IVHost)VHostSingleton.getInstance(IVHost.VHOST_DEFAULT);
    
    if (iVhost != null)
    {
        IPushPublishManager pushPublishManager = iVhost.getPushPublishManager();

        if (pushPublishManager != null)
        {
            HashMap<String,String> myEntryHashMap = new HashMap<String,String>();
            myEntryHashMap.put("sourceStreamName",<mystream>);
            ..... add all the necessary key/value pairs for your entry
            pushPublishManager.saveEntry(String appName, String entryName, myEntryHashMap );
        }
    }

If you have the PushPublishProfilesCustom.xml, your .jar file in the right places and have an entry in your applications pushpublish.map, when you start streaming the specified stream name, you should see entries in your logs related to it.

The example provided does the simple case of writing to the local disk for you to see what you need to do.  To write someplace else, you'll need to replace the code provided with your own implementation of how to write to your custom destination.

Hope this helps, 
Eric
