### ISSUE TITLE
Error with sample configuration

### ISSUE THREAD

**Issue by moticanvm** [WowzaMediaSystems/wse-example-pushpublish-hls#7]
Hi there,
We followed all steps, however, we get the following error in the wowza streaming engine error log. Also, no files or folders appearing in the file.root destination. Any ideas? Much appreciated!

>PushPublishUtils.startSessionForStream myStream[createClass]: Error creating push publishing implementation: com.wowza.wms.pushpublish.protocol.cupertino.PushPublishHTTPCupertinoFileHandler: : java.lang.ClassNotFoundException: com.wowza.wms.pushpublish.protocol.cupertino.PushPublishHTTPCupertinoFileHandler|at java.net.URLClassLoader.findClass(URLClassLoader.java:381)|at java.lang.ClassLoader.loadClass(ClassLoader.java:424)|at java.lang.ClassLoader.loadClass(ClassLoader.java:357)|at java.lang.Class.forName0(Native Method)|at java.lang.Class.forName(Class.java:264)|`

**Comment by rogerlittin** [comment]
Hi,

This is most likely due to a misconfigured `BaseClass` setting in your `PushPublishProfilesCustom.xml` file or there is a compile error when you compiled the example.

**Comment by moticanvm** [comment]
Thanks this helped. 

**However, we don't seem to be able to send to our CDN (KeyCDN) using the cupertino-http profile.**

**Keycdn**

- create keycdn zone - zone url wowzaengine-a1a1.kxcdn.com
- zone type - pull
- origin url - tried both http://wowzaengine.mydomain.com and http://wowzaengine.mydomain.com:1935



**wowza streaming engine, application's PushPublishMap.txt:**

> myStream={"entryName":"myStream", "profile":"cupertino-file", "streamName":"myOutputStream", "destinationName":"filesystem", "file.root":"/usr/local/WowzaStreamingEngine/conf/push_temp"}
> 
> myStream={"entryName":"myStream-http", "profile":"cupertino-http", "streamName":"myOutputStream", "destinationName":"webserver", "host":"wowzaengine-a1a1.kxcdn.com", "http.path":""}

=> tried http.path="hls" and http.path="

**get errors in wowzastreamingengine_error.log:**

> ERROR    server    comment    2018-03-13    11:49:20    -    - -    -    -    7366.8    -    -    -    -    -    -    -    - PushPublishHTTPCupertinoHTTPHandler.outputSend(test_test/_definst_/myStream->myOutputStream) Send media segment. rendition: AUDIOVIDEO chunkId:1 uri:7d48gglb/media_1.ts result:FAILURE
> WARN    server    comment    2018-03-13    11:49:30    -    - -    -    -    7376.623    -    -    -    -    -    -    -    - PushPublishHTTPCupertinoHTTPHandler.outputSend(test_test/_definst_/myStream->myOutputStream) Found 2 segments to send
> ERROR    server    comment    2018-03-13    11:49:30    -    - -    -    -    7376.677    -    -    -    -    -    -    -    - PushPublishHTTPCupertinoHTTPHandler.outputSend(test_test/_definst_/myStream->myOutputStream) Send media segment. rendition: AUDIOVIDEO chunkId:1 uri:7d48gglb/media_1.ts result:FAILURE
> WARN    server    comment    2018-03-13    11:49:40    -    - -    -    -    7386.836    -    -    -    -    -    -    -    - PushPublishHTTPCupertinoHTTPHandler.outputSend(test_test/_definst_/myStream->myOutputStream) Found 3 segments to send
> ERROR    server    comment    2018-03-13    11:49:40    -    - -    -    -    7386.89    -    -    -    -    -    -    -    - PushPublishHTTPCupertinoHTTPHandler.outputSend(test_test/_definst_/myStream->myOutputStream) Send media segment. rendition: AUDIOVIDEO chunkId:1 uri:7d48gglb/media_1.ts result:FAILURE
> WARN    server    comment    2018-03-13    11:49:50    -    - -    -    -    7396.849    -    -    -    -    -    -    -    - PushPublishHTTPCupertinoHTTPHandler.outputSend(test_test/_definst_/myStream->myOutputStream) Found 4 segments to send
> ERROR    server    comment    2018-03-13    11:49:51    -    - -    -    -    7396.929    -    -    -    -    -    -    -    - PushPublishHTTPCupertinoHTTPHandler.outputSend(test_test/_definst_/myStream->myOutputStream) Send media segment. rendition: AUDIOVIDEO chunkId:2 uri:7d48gglb/media_2.ts result:FAILURE 

- /usr/local/WowzaStreamingEngine/conf/push_temp exists, and can be written to
- /usr/local/WowzaStreamingEngine/conf/push_temp/myOutputStream/7d48gglb/media_1.ts, media_2.ts, ... exists
- /usr/local/WowzaStreamingEngine/conf/push_temp/myOutputStream/chunklist.m3u8 exists and is constantly updated
- /usr/local/WowzaStreamingEngine/conf/push_temp/myOutputStream/playlist.m3u8 exists and is constantly updated

Any ideas? Much appreciated!

**Comment by rogerlittin** [comment]
Does KeyCDN support Http PUSH or Http PUT?. From the configuration details you've provided, it looks like the cdn should be pulling the stream from your Wowza server, not the other way around (which is what this module does). You may need to configure your Wowza server as a Http Origin server and configure the cdn to pull the live stream.  See https://www.wowza.com/docs/how-to-configure-a-wowza-server-as-an-http-caching-origin.

**Comment by moticanvm** [comment]
Thanks for your response! KeyCDN should support http push. However, we switched to pull. Thanks again.

**Comment by ashokadk** [comment]
> Does KeyCDN support Http PUSH or Http PUT?. From the configuration details you've provided, it looks like the cdn should be pulling the stream from your Wowza server, not the other way around (which is what this module does). You may need to configure your Wowza server as a Http Origin server and configure the cdn to pull the live stream. See https://www.wowza.com/docs/how-to-configure-a-wowza-server-as-an-http-caching-origin.

I am running into a similar issue where I am not being able to send stream using the cupertino-http profile. I am getting a similar error:
`PushPublishHTTPCupertinoHTTPHandler.outputSend(packager/_definst_/test.mpegts.out.stream->ashok.stream) Send media segment. rendition: AUDIOVIDEO chunkId:1 uri:i2l75e11/media_1.ts result:FAILURE`
In my setup, I am trying to push the stream from a wowza live server to wowza live edge. Do I need to instead push the stream to Http Origin?
