### ISSUE TITLE
The playlist file was not sent

### ISSUE THREAD

**Issue by Tkamiya** [WowzaMediaSystems/wse-example-pushpublish-hls#8]
Hello,

I have tried your example of pushpublish hls jre file with Wowza 4.7.6 for AmazonS3.
Then I confirmed the .ts files were sent in there properly but the .m3u8 playlist file did not.

Would you check it?

**Comment by rogerlittin** [comment]
Hi,

I've just rebuilt the jar file against 4.7.6 in case there were any changes. Please retest with the latest version. If you're still having problems then please enable debug logging for your Stream Target and run a test. Please open a support ticket and upload the conf & logs folders along with a description of the problem.

Thanks,

Roger.

**Comment by Tkamiya** [comment]
Hi Roger,

Thank you for your help.

Unfortunately, there is still problem in spite of replaced to your latest jre file...

Therefore, I have enabled the debug logging for Stream Target.
I referred to the following instruction.
https://www.wowza.com/docs/how-to-debug-push-publishing
Is this correct one?
And also, where can I find the debug log? After enabled the pushPublishDebug in my live application, I expected a debug log file will be output in logs folder.
However, I could not find out the debug log in logs folder.

If it is correct, then I will send my log files to your support team.

**Comment by rogerlittin** [comment]
Yes, that is correct. The logging should be written to the `wowzastreamingengine_access.log` file.

**Comment by Tkamiya** [comment]
Thank you very much. I have sent the log files to support team.

**Comment by Tkamiya** [comment]
I have confirmed a new thing. The local file output feature works properly. Just in case.

**Comment by rogerlittin** [comment]
I think I have fixed it. The playback urls have `../`but we weren't stripping this out before creating the upload urls. This looks like it was causing problems with S3. I also changed it in the local file handler because it isn't necessary.

**Comment by rogerlittin** [comment]
As of Wowza Streaming Engine 4.7.6, the `adaptiveGroups` (plural) Stream Target key is deprecated. This has been replaced by the `adaptiveGroup` (singular) key which should be used instead. There is a bug in 4.7.6 where the deprecated key should still work but it doesn't and this will be resolved in 4.7.6.01. In the meantime, renaming the deprecated key to the new name in each map entry that uses it will fix the issue. The bug prevents the group master playlist from being uploaded if the old key name is used.
